oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT > Class Template Reference
Pseudo-elasticity version of the LineFluidInterfaceBoundingElement.
#include <specific_node_update_interface_elements.h>
Public Member Functions
void set_lagrange_index (const Vector< unsigned > &lagrange_index)
Set the Id.
ElasticLineFluidInterfaceBoundingElement ()
Constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output the element.
void output (FILE *file_pt)
Overload the C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style Output function.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the elemental residual vector and Jacobian.
int kinematic_local_eqn (const unsigned &n)
Local eqn number of kinematic bc associated with local node n.
Public Member Functions inherited from oomph::LineFluidInterfaceBoundingElement
LineFluidInterfaceBoundingElement ()
Constructor.
Public Member Functions inherited from oomph::FluidInterfaceBoundingElement
FluidInterfaceBoundingElement ()
Constructor.
WallUnitNormalFctPt & wall_unit_normal_fct_pt ()
Access function: Pointer to wall unit normal function.
WallUnitNormalFctPt wall_unit_normal_fct_pt () const
Access function: Pointer to wall unit normal function. Const version.
Vector< unsigned > & u_index_interface_boundary ()
Access for nodal index at which the velocity components are stored.
void set_contact_angle (double *const &angle_pt, const bool &strong=true)
Set a pointer to the desired contact angle. Optional boolean (defaults to true) chooses strong imposition via hijacking (true) or weak imposition via addition to momentum equation (false). The default strong imposition is appropriate for static contact angle problems.
double *& contact_angle_pt ()
Access function to the pointer specifying the prescribed contact angle.
double *& ca_pt ()
Access function to the pointer specifying the capillary number.
double ca ()
Return the value of the capillary number.
double & contact_angle ()
Return value of the contact angle.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Calculate the residuals.
virtual void fill_in_generic_residual_contribution_interface_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)=0
Calculate the generic residuals contribution.
virtual void add_additional_residual_contributions_interface_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const Vector< double > &interpolated_n, const double &W)
Empty helper function to calculate the additional contributions arising from the node update strategy to the Jacobian within the integration loop. This will be overloaded by elements that require contributions to their underlying equations from boundary integrals. The shape functions, their derivatives w.r.t. to the local coordinates, the unit normal and integral weight are passed in so that they do not have to be recalculated.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style Output function.
Private Attributes
Vector< unsigned > Lagrange_index
Short Storage for the index of Lagrange multiplier.
Additional Inherited Members
Protected Member Functions inherited from oomph::LineFluidInterfaceBoundingElement
void fill_in_generic_residual_contribution_interface_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Overload the helper function to calculate the residuals and (if flag==true) the Jacobian -- this function only deals with the part of the Jacobian that can be handled generically. Specific additional contributions may be provided in add_additional_residual_contributions_interface_boundary()
Protected Member Functions inherited from oomph::FluidInterfaceBoundingElement
virtual int kinematic_local_eqn (const unsigned &n)=0
Function that is used to determine the local equation number of the kinematic equation associated with the nodes of the element This must be overloaded depending on the node update scheme.
void wall_unit_normal (const Vector< double > &x, Vector< double > &normal)
Function that returns the unit normal of the bounding wall directed out of the fluid.
void update_in_external_fd (const unsigned &i)
The geometric data of the parent element is included as external data and so a (bulk) node update must take place after the variation of any of this external data.
void reset_in_external_fd (const unsigned &i)
The only external data are these geometric data so We can omit the reset function (relying on the next update.
void reset_after_external_fd ()
We require a final node update in the bulk element after all finite differencing.
Protected Attributes inherited from oomph::FluidInterfaceBoundingElement
unsigned Contact_angle_flag
Flag used to determine whether the contact angle is to be used (0 if not), and whether it will be applied weakly as a force term in the momentum equations (1) or by hijacking the kinematic condition (2).
Vector< unsigned > U_index_interface_boundary
Index at which the i-th velocity component is stored in the element's nodes.
Detailed Description
template<class ELEMENT>
class oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >
Pseudo-elasticity version of the LineFluidInterfaceBoundingElement.
Definition at line 1126 of file specific_node_update_interface_elements.h.
Constructor & Destructor Documentation
ElasticLineFluidInterfaceBoundingElement()
template<class ELEMENT >
oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::ElasticLineFluidInterfaceBoundingElement () [inline]
Constructor.
Definition at line 1143 of file specific_node_update_interface_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Calculate the elemental residual vector and Jacobian.
Definition at line 1186 of file specific_node_update_interface_elements.h.
References oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary().
kinematic_local_eqn()
template<class ELEMENT >
int oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn (const unsigned & n) [inline], [virtual]
Local eqn number of kinematic bc associated with local node n.
Implements oomph::FluidInterfaceBoundingElement.
Definition at line 1202 of file specific_node_update_interface_elements.h.
output() [1/4]
template<class ELEMENT >
void oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::output (FILE * file_pt) [inline]
Overload the C-style output function.
Definition at line 1174 of file specific_node_update_interface_elements.h.
output() [2/4]
template<class ELEMENT >
void oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline]
C-style Output function.
Definition at line 1180 of file specific_node_update_interface_elements.h.
References oomph::FluidInterfaceBoundingElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::output (std::ostream & outfile) [inline]
Overload the output function.
Definition at line 1162 of file specific_node_update_interface_elements.h.
output() [4/4]
template<class ELEMENT >
void oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline]
Output the element.
Definition at line 1168 of file specific_node_update_interface_elements.h.
References oomph::FluidInterfaceBoundingElement::output().
set_lagrange_index()
template<class ELEMENT >
void oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::set_lagrange_index (const Vector< unsigned > & lagrange_index) [inline]
Set the Id.
Definition at line 1137 of file specific_node_update_interface_elements.h.
References oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::Lagrange_index.
zeta_nodal()
template<class ELEMENT >
double oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
Definition at line 1153 of file specific_node_update_interface_elements.h.
Member Data Documentation
Lagrange_index
template<class ELEMENT >
Vector<unsigned> oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::Lagrange_index [private]
Short Storage for the index of Lagrange multiplier.
Definition at line 1133 of file specific_node_update_interface_elements.h.
Referenced by oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::set_lagrange_index().
The documentation for this class was generated from the following file:
specific_node_update_interface_elements.h