oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT > Class Template Reference
Spine version of the PointFluidInterfaceBoundingElement.
#include <specific_node_update_interface_elements.h>
Public Member Functions
SpinePointFluidInterfaceBoundingElement ()
Constructor.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output the element.
void output (FILE *file_pt)
Overload the C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style Output function.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the elemental residual vector and the Jacobian.
int kinematic_local_eqn (const unsigned &n)
Return local equation number associated with the kinematic constraint for local node n.
Public Member Functions inherited from oomph::PointFluidInterfaceBoundingElement
PointFluidInterfaceBoundingElement ()
Constructor.
Public Member Functions inherited from oomph::FluidInterfaceBoundingElement
FluidInterfaceBoundingElement ()
Constructor.
WallUnitNormalFctPt & wall_unit_normal_fct_pt ()
Access function: Pointer to wall unit normal function.
WallUnitNormalFctPt wall_unit_normal_fct_pt () const
Access function: Pointer to wall unit normal function. Const version.
Vector< unsigned > & u_index_interface_boundary ()
Access for nodal index at which the velocity components are stored.
void set_contact_angle (double *const &angle_pt, const bool &strong=true)
Set a pointer to the desired contact angle. Optional boolean (defaults to true) chooses strong imposition via hijacking (true) or weak imposition via addition to momentum equation (false). The default strong imposition is appropriate for static contact angle problems.
double *& contact_angle_pt ()
Access function to the pointer specifying the prescribed contact angle.
double *& ca_pt ()
Access function to the pointer specifying the capillary number.
double ca ()
Return the value of the capillary number.
double & contact_angle ()
Return value of the contact angle.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Calculate the residuals.
virtual void fill_in_generic_residual_contribution_interface_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)=0
Calculate the generic residuals contribution.
virtual void add_additional_residual_contributions_interface_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const Vector< double > &interpolated_n, const double &W)
Empty helper function to calculate the additional contributions arising from the node update strategy to the Jacobian within the integration loop. This will be overloaded by elements that require contributions to their underlying equations from boundary integrals. The shape functions, their derivatives w.r.t. to the local coordinates, the unit normal and integral weight are passed in so that they do not have to be recalculated.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style Output function.
Additional Inherited Members
Protected Member Functions inherited from oomph::PointFluidInterfaceBoundingElement
void fill_in_generic_residual_contribution_interface_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Overload the helper function to calculate the residuals and (if flag==1) the Jacobian -- this function only deals with the part of the Jacobian that can be handled generically. Specific additional contributions may be provided in add_additional_residual_contributions_interface_boundary(...)
Protected Member Functions inherited from oomph::FluidInterfaceBoundingElement
virtual int kinematic_local_eqn (const unsigned &n)=0
Function that is used to determine the local equation number of the kinematic equation associated with the nodes of the element This must be overloaded depending on the node update scheme.
void wall_unit_normal (const Vector< double > &x, Vector< double > &normal)
Function that returns the unit normal of the bounding wall directed out of the fluid.
void update_in_external_fd (const unsigned &i)
The geometric data of the parent element is included as external data and so a (bulk) node update must take place after the variation of any of this external data.
void reset_in_external_fd (const unsigned &i)
The only external data are these geometric data so We can omit the reset function (relying on the next update.
void reset_after_external_fd ()
We require a final node update in the bulk element after all finite differencing.
Protected Attributes inherited from oomph::FluidInterfaceBoundingElement
unsigned Contact_angle_flag
Flag used to determine whether the contact angle is to be used (0 if not), and whether it will be applied weakly as a force term in the momentum equations (1) or by hijacking the kinematic condition (2).
Vector< unsigned > U_index_interface_boundary
Index at which the i-th velocity component is stored in the element's nodes.
Detailed Description
template<class ELEMENT>
class oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >
Spine version of the PointFluidInterfaceBoundingElement.
Definition at line 421 of file specific_node_update_interface_elements.h.
Constructor & Destructor Documentation
SpinePointFluidInterfaceBoundingElement()
template<class ELEMENT >
oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::SpinePointFluidInterfaceBoundingElement () [inline]
Constructor.
Definition at line 428 of file specific_node_update_interface_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Calculate the elemental residual vector and the Jacobian.
Definition at line 459 of file specific_node_update_interface_elements.h.
References oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary().
kinematic_local_eqn()
template<class ELEMENT >
int oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn (const unsigned & n) [inline], [virtual]
Return local equation number associated with the kinematic constraint for local node n.
Implements oomph::FluidInterfaceBoundingElement.
Definition at line 474 of file specific_node_update_interface_elements.h.
output() [1/4]
template<class ELEMENT >
void oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::output (FILE * file_pt) [inline]
Overload the C-style output function.
Definition at line 447 of file specific_node_update_interface_elements.h.
output() [2/4]
template<class ELEMENT >
void oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline]
C-style Output function.
Definition at line 453 of file specific_node_update_interface_elements.h.
References oomph::FluidInterfaceBoundingElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::output (std::ostream & outfile) [inline]
Overload the output function.
Definition at line 435 of file specific_node_update_interface_elements.h.
output() [4/4]
template<class ELEMENT >
void oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline]
Output the element.
Definition at line 441 of file specific_node_update_interface_elements.h.
References oomph::FluidInterfaceBoundingElement::output().
The documentation for this class was generated from the following file:
specific_node_update_interface_elements.h