oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT > Class Template Reference
Spine-based Marangoni surface tension elements that add a linear dependence on concentration of a surface chemical to the surface tension, which decreases with increasing concentration. The non-dimensionalisation is the same as Campana et al (2004) but we may wish to revisit this.
Public Member Functions
SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement (FiniteElement *const &element_pt, const int &face_index)
Constructor that passes the bulk element and face index down to the underlying.
double beta ()
Return the Elasticity number.
double peclet_s ()
Return the surface peclect number.
double peclet_strouhal_s ()
Return the surface peclect strouhal number.
double *& beta_pt ()
Access function for pointer to the Elasticity number.
double *& peclet_s_pt ()
Access function for pointer to the surface Peclet number.
double *& peclet_strouhal_s_pt ()
Access function for pointer to the surface Peclet x Strouhal number.
void output (std::ostream &outfile, const unsigned &n_plot)
double integrate_c () const
Compute the concentration intergated over the area.
Public Member Functions inherited from oomph::SpineAxisymmetricFluidInterfaceElement< ELEMENT >
SpineAxisymmetricFluidInterfaceElement (FiniteElement *const &element_pt, const int &face_index)
Public Member Functions inherited from oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >
SpineUpdateFluidInterfaceElement (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0)
Constructor, the arguments are a pointer to the `bulk` element and the index of the face to be created.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the contribution to the residuals and the jacobian.
void add_additional_residual_contributions_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const DShape &dpsifdS, const DShape &dpsifdS_div, const Vector< double > &s, const Vector< double > &interpolated_x, const Vector< double > &interpolated_n, const double &W, const double &J)
Helper function to calculate the additional contributions These are those filled in by the particular equations.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output the element.
void output (FILE *file_pt)
Overload the C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style Output function.
virtual FluidInterfaceBoundingElement * make_bounding_element (const int &face_index)
Create an `bounding` element of the type specified by the BoundingElementType policy class Here, this allows the application of a contact angle boundary condition on the the specified face.
Public Member Functions inherited from oomph::FluidInterfaceElement
FluidInterfaceElement ()
Constructor, set the default values of the booleans and pointers (null)
virtual double sigma (const Vector< double > &s_local)
Virtual function that specifies the non-dimensional surface tension as a function of local position within the element. The default behaviour is a constant surface tension of value 1.0 This function can be overloaded in more specialised elements to incorporate variations in surface tension.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Calculate the residuals by calling the generic residual contribution.
const double & ca () const
The value of the Capillary number.
double *& ca_pt ()
Pointer to the Capillary number.
const double & st () const
The value of the Strouhal number.
double *& st_pt ()
The pointer to the Strouhal number.
double u (const unsigned &j, const unsigned &i)
Return the i-th velocity component at local node j.
double interpolated_u (const Vector< double > &s, const unsigned &i)
Calculate the i-th velocity component at the local coordinate s.
double pext () const
Return the value of the external pressure.
void set_external_pressure_data (Data *external_pressure_data_pt)
Set the Data that contains the single pressure value that specifies the `external pressure` for the interface/free-surface. Setting this only makes sense if the interface is, in fact, a free surface (well, an interface to another inviscid fluid if you want to be picky).
void set_external_pressure_data (Data *external_pressure_data_pt, const unsigned &index_of_external_pressure_value)
Set the Data that contains the pressure value that specifies the `external pressure` for the interface/free-surface. Setting this only makes sense if the interface is, in fact, a free surface (well, an interface to another inviscid fluid if you want to be picky). Second argument specifies the index of the pressure value within the Data object.
virtual FluidInterfaceBoundingElement * make_bounding_element (const int &face_index)
Create a bounding element e.g. to apply a contact angle boundary condition.
virtual void hijack_kinematic_conditions (const Vector< unsigned > &bulk_node_number)=0
Hijack the kinematic condition at the node numbers passed in the vector. The node numbers correspond to the local numbers of nodes in the associated bulk element. This is required so that contact-angle conditions can be applied by the FluidInterfaceBoundingElements.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style Output function.
Public Member Functions inherited from oomph::AxisymmetricDerivatives
AxisymmetricDerivatives ()
Protected Member Functions
double interpolated_C (const Vector< double > &s)
Get the surfactant concentration.
double dcdt_surface (const unsigned &l) const
The time derivative of the surface concentration.
double sigma (const Vector< double > &s)
The surface tension function is linear in the concentration with constant of proportionality equal to the elasticity number.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in the contribution to the residuals Calculate the contribution to the jacobian.
void add_additional_residual_contributions_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const DShape &dpsifdS, const DShape &dpsifdS_div, const Vector< double > &s, const Vector< double > &interpolated_x, const Vector< double > &interpolated_n, const double &W, const double &J)
Overload the Helper function to calculate the residuals and jacobian entries. This particular function ensures that the additional entries are calculated inside the integration loop.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Protected Member Functions inherited from oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >
double compute_surface_derivatives (const Shape &psi, const DShape &dpsids, const DenseMatrix< double > &interpolated_t, const Vector< double > &interpolated_x, DShape &surface_gradient, DShape &surface_divergence)
Fill in the specific surface derivative calculations by calling the appropriate class function.
Protected Member Functions inherited from oomph::FluidInterfaceElement
virtual int kinematic_local_eqn (const unsigned &n)=0
Access function that returns the local equation number for the (scalar) kinematic equation associated with the j-th local node. This must be overloaded by specific interface elements and depends on the method for handing the free-surface deformation.
int pext_local_eqn ()
Access function for the local equation number that corresponds to the external pressure.
virtual void fill_in_generic_residual_contribution_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Helper function to calculate the residuals and (if flag==1) the Jacobian of the equations. This is implemented generically using the surface divergence information that is overloaded in each element i.e. axisymmetric, two- or three-dimensional.
virtual double compute_surface_derivatives (const Shape &psi, const DShape &dpsids, const DenseMatrix< double > &interpolated_t, const Vector< double > &interpolated_x, DShape &dpsidS, DShape &dpsidS_div)=0
Compute the surface gradient and surface divergence operators given the shape functions, derivatives, tangent vectors and position. All derivatives and tangent vectors should be formed with respect to the local coordinates.
virtual void add_additional_residual_contributions_interface (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag, const Shape &psif, const DShape &dpsifds, const DShape &dpsifdS, const DShape &dpsifdS_div, const Vector< double > &s, const Vector< double > &interpolated_x, const Vector< double > &interpolated_n, const double &W, const double &J)
Helper function to calculate the additional contributions to the resisuals and Jacobian that arise from specific node update strategies. This is called within the integration loop over the element (for efficiency) and therefore requires a fairly large number of input parameters:
Protected Member Functions inherited from oomph::AxisymmetricDerivatives
double compute_surface_derivatives (const Shape &psi, const DShape &dpsids, const DenseMatrix< double > &interpolated_t, const Vector< double > &interpolated_x, DShape &surface_gradient, DShape &surface_divergence)
Fill in the specific surface derivative calculations.
Private Attributes
double * Beta_pt
Pointer to an Elasticity number.
double * Peclet_S_pt
Pointer to Surface Peclet number.
double * Peclet_Strouhal_S_pt
Pointer to the surface Peclect Strouhal number.
unsigned C_index
Index at which the surfactant concentration is stored at the nodes.
Static Private Attributes
static double Default_Physical_Constant_Value = 1.0
Default value of the physical constants.
Additional Inherited Members
Protected Attributes inherited from oomph::FluidInterfaceElement
Vector< unsigned > U_index_interface
Nodal index at which the i-th velocity component is stored.
int External_data_number_of_external_pressure
The Data that contains the external pressure is stored as external Data for the element. Which external Data item is it? (int so it can be initialised to -1, indicating that external pressure hasn't been set).
Data * Pext_data_pt
Pointer to the Data item that stores the external pressure.
unsigned Index_of_external_pressure_value
Which of the values in Pext_data_pt stores the external pressure.
Detailed Description
template<class ELEMENT>
class oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >
Spine-based Marangoni surface tension elements that add a linear dependence on concentration of a surface chemical to the surface tension, which decreases with increasing concentration. The non-dimensionalisation is the same as Campana et al (2004) but we may wish to revisit this.
Definition at line 115 of file rayleigh_instability_insoluble_surfactant.cc.
Constructor & Destructor Documentation
SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement()
template<class ELEMENT >
oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor that passes the bulk element and face index down to the underlying.
Definition at line 532 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Beta_pt, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Default_Physical_Constant_Value, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_S_pt, and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_Strouhal_S_pt.
Member Function Documentation
add_additional_residual_contributions_interface()
template<class ELEMENT >
void oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag, const Shape & psif, const DShape & dpsifds, const DShape & dpsifdS, const DShape & dpsifdS_div, const Vector< double > & s, const Vector< double > & interpolated_x, const Vector< double > & interpolated_n, const double & W, const double & J) [inline], [protected], [virtual]
Overload the Helper function to calculate the residuals and jacobian entries. This particular function ensures that the additional entries are calculated inside the integration loop.
Reimplemented from oomph::FluidInterfaceElement.
Definition at line 279 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::dcdt_surface(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C(), oomph::FluidInterfaceElement::interpolated_u(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s(), and oomph::FluidInterfaceElement::U_index_interface.
beta()
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta () [inline]
Return the Elasticity number.
Definition at line 558 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Beta_pt.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma().
beta_pt()
template<class ELEMENT >
double *& oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta_pt () [inline]
Access function for pointer to the Elasticity number.
Definition at line 567 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Beta_pt.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
dcdt_surface()
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::dcdt_surface (const unsigned & l) const [inline], [protected]
The time derivative of the surface concentration.
Definition at line 165 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface().
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [protected]
Fill in the contribution to the residuals Calculate the contribution to the jacobian.
Definition at line 215 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index, and oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface().
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class ELEMENT >
void oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [protected]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 521 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian().
integrate_c()
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::integrate_c () const [inline]
Compute the concentration intergated over the area.
Definition at line 627 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::compute_total_mass().
interpolated_C()
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C (const Vector< double > & s) [inline], [protected]
Get the surfactant concentration.
Definition at line 138 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::output().
output()
template<class ELEMENT >
void oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline]
Definition at line 575 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C(), oomph::FluidInterfaceElement::interpolated_u(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma().
peclet_s()
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s () [inline]
Return the surface peclect number.
Definition at line 561 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_S_pt.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface().
peclet_s_pt()
template<class ELEMENT >
double *& oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s_pt () [inline]
Access function for pointer to the surface Peclet number.
Definition at line 570 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_S_pt.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
peclet_strouhal_s()
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s () [inline]
Return the surface peclect strouhal number.
Definition at line 564 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_Strouhal_S_pt.
peclet_strouhal_s_pt()
template<class ELEMENT >
double *& oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s_pt () [inline]
Access function for pointer to the surface Peclet x Strouhal number.
Definition at line 573 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_Strouhal_S_pt.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
sigma()
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma (const Vector< double > & s) [inline], [protected], [virtual]
The surface tension function is linear in the concentration with constant of proportionality equal to the elasticity number.
Reimplemented from oomph::FluidInterfaceElement.
Definition at line 192 of file rayleigh_instability_insoluble_surfactant.cc.
References oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::output().
Member Data Documentation
Beta_pt
template<class ELEMENT >
double* oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Beta_pt [private]
Pointer to an Elasticity number.
Definition at line 120 of file rayleigh_instability_insoluble_surfactant.cc.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta_pt(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement().
C_index
template<class ELEMENT >
unsigned oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::C_index [private]
Index at which the surfactant concentration is stored at the nodes.
Definition at line 130 of file rayleigh_instability_insoluble_surfactant.cc.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::add_additional_residual_contributions_interface(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::dcdt_surface(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::integrate_c(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::interpolated_C(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement().
Default_Physical_Constant_Value
template<class ELEMENT >
double oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Default_Physical_Constant_Value = 1.0 [static], [private]
Default value of the physical constants.
Definition at line 133 of file rayleigh_instability_insoluble_surfactant.cc.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement().
Peclet_S_pt
template<class ELEMENT >
double* oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_S_pt [private]
Pointer to Surface Peclet number.
Definition at line 123 of file rayleigh_instability_insoluble_surfactant.cc.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s_pt(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement().
Peclet_Strouhal_S_pt
template<class ELEMENT >
double* oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::Peclet_Strouhal_S_pt [private]
Pointer to the surface Peclect Strouhal number.
Definition at line 126 of file rayleigh_instability_insoluble_surfactant.cc.
Referenced by oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s_pt(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement().
The documentation for this class was generated from the following file:
rayleigh_instability_insoluble_surfactant.cc