oomph::TetMeshFacetedClosedSurface Class Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <tet_mesh.h>
Public Member Functions
TetMeshFacetedClosedSurface ()
Constructor:
virtual ~TetMeshFacetedClosedSurface ()
Empty destructor.
void enable_faceted_volume_represents_hole_for_gmsh ()
Declare closed surface to represent hole for gmsh.
void disable_faceted_volume_represents_hole_for_gmsh ()
Declare closed surface NOT to represent hole for gmsh.
bool faceted_volume_represents_hole_for_gmsh () const
Does closed surface represent hole for gmsh?
const double & internal_point_for_tetgen (const unsigned &j, const unsigned &i) const
i=th coordinate of the j-th internal point for tetgen
void set_hole_for_tetgen (const Vector< double > &hole_point)
Specify coordinate of hole for tetgen.
void set_region_for_tetgen (const unsigned &region_id, const Vector< double > &region_point)
Specify a region; pass (zero-based) region ID and coordinate of point in region for tetgen.
unsigned ninternal_point_for_tetgen ()
Number of internal points (identifying either regions or holes) for tetgen.
const int & region_id_for_tetgen (const unsigned &j) const
Return the (zero-based) region ID of j-th internal point for tetgen. Negative if it's actually a hole.
bool internal_point_identifies_hole_for_tetgen (const unsigned &j)
Is j-th internal point for tetgen associated with a hole?
bool internal_point_identifies_region_for_tetgen (const unsigned &j)
Is j-th internal point for tetgen associated with a region?
Public Member Functions inherited from oomph::TetMeshFacetedSurface
TetMeshFacetedSurface ()
Constructor:
virtual ~TetMeshFacetedSurface ()
Empty destructor.
unsigned nvertex () const
Number of vertices.
unsigned nfacet () const
Number of facets.
unsigned one_based_facet_boundary_id (const unsigned &j) const
One-based boundary id of j-th facet.
unsigned one_based_vertex_boundary_id (const unsigned &j) const
First (of possibly multiple) one-based boundary id of j-th vertex.
double vertex_coordinate (const unsigned &j, const unsigned &i) const
i-th coordinate of j-th vertex
unsigned nvertex_on_facet (const unsigned &j) const
Number of vertices defining the j-th facet.
bool boundaries_can_be_split_in_tetgen ()
Test whether boundary can be split in tetgen.
void enable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
void disable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
TetMeshFacet * facet_pt (const unsigned &j) const
Pointer to j-th facet.
TetMeshVertex * vertex_pt (const unsigned &j) const
Pointer to j-th vertex.
DiskLikeGeomObjectWithBoundaries * geom_object_with_boundaries_pt ()
Access to GeomObject with boundaries associated with this surface (Null if there isn't one!)
void output (std::ostream &outfile) const
Output.
void output (const std::string &filename) const
Output.
virtual void boundary_zeta01 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 0 and 1 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 0; zeta_boundary=1.0: we're on vertex 1.
virtual void boundary_zeta12 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 1 and 2 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 1; zeta_boundary=1.0: we're on vertex 2.
virtual void boundary_zeta20 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 2 and 0 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 2; zeta_boundary=1.0: we're on vertex 0.
Vector< unsigned > vertex_index_in_tetgen (const unsigned &f)
Facet connectivity: vertex_index[j] is the index of the j-th vertex (in the Vertex_pt vector) in facet f. Bit of an obscure functionality that's only needed for setup tetgen_io.
Private Attributes
Vector< std::pair< Vector< double >, int > > Internal_point_for_tetgen
Storage for internal points for tetgen. Stores pair of: -- Vector containing coordinates of internal point -- region ID (negative if it's a hole)
bool Faceted_volume_represents_hole_for_gmsh
Does closed surface represent hole for gmsh?
Additional Inherited Members
Protected Attributes inherited from oomph::TetMeshFacetedSurface
Vector< TetMeshVertex * > Vertex_pt
Vector pointers to vertices.
Vector< TetMeshFacet * > Facet_pt
Vector of pointers to facets.
bool Boundaries_can_be_split_in_tetgen
Boolean to indicate whether extra vertices can be added on the boundary in tetgen.
Vector< Vector< unsigned > > Facet_vertex_index_in_tetgen
Facet connectivity: Facet_vertex_index[f][j] is the index of the j-th vertex (in the Vertex_pt vector) in facet f.
DiskLikeGeomObjectWithBoundaries * Geom_object_with_boundaries_pt
GeomObject with boundaries associated with this surface.
Detailed Description
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Base class for closed tet mesh boundary bounded by polygonal planar facets
Definition at line 537 of file tet_mesh.h.
Constructor & Destructor Documentation
TetMeshFacetedClosedSurface()
oomph::TetMeshFacetedClosedSurface::TetMeshFacetedClosedSurface () [inline]
Constructor:
Definition at line 541 of file tet_mesh.h.
 TetMeshFacetedClosedSurface()
virtual oomph::TetMeshFacetedClosedSurface::~TetMeshFacetedClosedSurface () [inline], [virtual]
Empty destructor.
Definition at line 547 of file tet_mesh.h.
Member Function Documentation
disable_faceted_volume_represents_hole_for_gmsh()
void oomph::TetMeshFacetedClosedSurface::disable_faceted_volume_represents_hole_for_gmsh () [inline]
Declare closed surface NOT to represent hole for gmsh.
Definition at line 556 of file tet_mesh.h.
References Faceted_volume_represents_hole_for_gmsh.
enable_faceted_volume_represents_hole_for_gmsh()
void oomph::TetMeshFacetedClosedSurface::enable_faceted_volume_represents_hole_for_gmsh () [inline]
Declare closed surface to represent hole for gmsh.
Definition at line 550 of file tet_mesh.h.
References Faceted_volume_represents_hole_for_gmsh.
faceted_volume_represents_hole_for_gmsh()
bool oomph::TetMeshFacetedClosedSurface::faceted_volume_represents_hole_for_gmsh () const [inline]
Does closed surface represent hole for gmsh?
Definition at line 562 of file tet_mesh.h.
References Faceted_volume_represents_hole_for_gmsh.
Referenced by oomph::GmshTetScaffoldMesh::write_geo_file().
internal_point_for_tetgen()
const double & oomph::TetMeshFacetedClosedSurface::internal_point_for_tetgen (const unsigned & j, const unsigned & i) const [inline]
i=th coordinate of the j-th internal point for tetgen
Definition at line 568 of file tet_mesh.h.
References i, and Internal_point_for_tetgen.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio().
internal_point_identifies_hole_for_tetgen()
bool oomph::TetMeshFacetedClosedSurface::internal_point_identifies_hole_for_tetgen (const unsigned & j) [inline]
Is j-th internal point for tetgen associated with a hole?
Definition at line 605 of file tet_mesh.h.
References Internal_point_for_tetgen.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio().
internal_point_identifies_region_for_tetgen()
bool oomph::TetMeshFacetedClosedSurface::internal_point_identifies_region_for_tetgen (const unsigned & j) [inline]
Is j-th internal point for tetgen associated with a region?
Definition at line 611 of file tet_mesh.h.
References Internal_point_for_tetgen.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
ninternal_point_for_tetgen()
unsigned oomph::TetMeshFacetedClosedSurface::ninternal_point_for_tetgen () [inline]
Number of internal points (identifying either regions or holes) for tetgen.
Definition at line 591 of file tet_mesh.h.
References Internal_point_for_tetgen.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
region_id_for_tetgen()
const int & oomph::TetMeshFacetedClosedSurface::region_id_for_tetgen (const unsigned & j) const [inline]
Return the (zero-based) region ID of j-th internal point for tetgen. Negative if it's actually a hole.
Definition at line 598 of file tet_mesh.h.
References Internal_point_for_tetgen.
Referenced by oomph::TetgenMesh< ELEMENT >::build_tetgenio().
set_hole_for_tetgen()
void oomph::TetMeshFacetedClosedSurface::set_hole_for_tetgen (const Vector< double > & hole_point) [inline]
Specify coordinate of hole for tetgen.
Definition at line 575 of file tet_mesh.h.
References Internal_point_for_tetgen.
set_region_for_tetgen()
void oomph::TetMeshFacetedClosedSurface::set_region_for_tetgen (const unsigned & region_id, const Vector< double > & region_point) [inline]
Specify a region; pass (zero-based) region ID and coordinate of point in region for tetgen.
Definition at line 582 of file tet_mesh.h.
References Internal_point_for_tetgen.
Member Data Documentation
Faceted_volume_represents_hole_for_gmsh
bool oomph::TetMeshFacetedClosedSurface::Faceted_volume_represents_hole_for_gmsh [private]
Does closed surface represent hole for gmsh?
Definition at line 624 of file tet_mesh.h.
Referenced by disable_faceted_volume_represents_hole_for_gmsh(), enable_faceted_volume_represents_hole_for_gmsh(), and faceted_volume_represents_hole_for_gmsh().
Internal_point_for_tetgen
Vector<std::pair<Vector<double>, int> > oomph::TetMeshFacetedClosedSurface::Internal_point_for_tetgen [private]
Storage for internal points for tetgen. Stores pair of: -- Vector containing coordinates of internal point -- region ID (negative if it's a hole)
Definition at line 621 of file tet_mesh.h.
Referenced by internal_point_for_tetgen(), internal_point_identifies_hole_for_tetgen(), internal_point_identifies_region_for_tetgen(), ninternal_point_for_tetgen(), region_id_for_tetgen(), set_hole_for_tetgen(), and set_region_for_tetgen().
The documentation for this class was generated from the following file:
tet_mesh.h