oomph::ANASAZI Class Reference
Class for the Anasazi eigensolver.
#include <trilinos_eigen_solver.h>
Public Member Functions
ANASAZI ()
Constructor.
ANASAZI (const ANASAZI &)
Empty copy constructor.
virtual ~ANASAZI ()
Destructor, delete the linear solver.
void solve_eigenproblem (Problem *const &problem_pt, const int &n_eval, Vector< std::complex< double > > &alpha, Vector< double > &beta, Vector< DoubleVector > &eigenvector_real, Vector< DoubleVector > &eigenvector_imag, const bool &do_adjoint_problem)
Solve the real eigenproblem that is assembled by elements in a mesh in a Problem object. Note that the assembled matrices include the shift and are real. The eigenvalues and eigenvectors are, in general, complex. Eigenvalues may be infinite and are therefore returned as $ \lambda_i = \alpha_i / \beta_i $ where $ \alpha_i $ is complex while $ \beta_i $ is real. The actual eigenvalues may then be computed by doing the division, checking for zero betas to avoid NaNs. There's a convenience wrapper to this function that simply computes these eigenvalues regardless. That version may die in NaN checking is enabled (via the fenv.h header and the associated feenable function). NOTE: While the above statement is true, the implementation of this function is actually everse engineered -- trilinos actually computes the eigenvalues directly (and being an Arnoldi method it wouldn't be able to obtain any infinite/NaN eigenvalues anyway.
void solve_eigenproblem (Problem *const &problem_pt, const int &n_eval, Vector< std::complex< double > > &eigenvalue, Vector< DoubleVector > &eigenvector_real, Vector< DoubleVector > &eigenvector_imag, const bool &do_adjoint_problem)
Solve the eigen problem.
void solve_eigenproblem_legacy (Problem *const &problem_pt, const int &n_eval, Vector< std::complex< double > > &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &do_adjoint_problem)
Solve the eigen problem.
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
Public Member Functions inherited from oomph::EigenSolver
EigenSolver ()
Empty constructor.
EigenSolver (const EigenSolver &)
Empty copy constructor.
virtual ~EigenSolver ()
Empty destructor.
virtual void solve_eigenproblem_legacy (Problem *const &problem_pt, const int &n_eval, Vector< std::complex< double > > &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &do_adjoint_problem=false)=0
Eigensolver. This takes a pointer to a problem and returns a vector of complex numbers representing the eigenvalues and a corresponding vector of eigenvectors. n_eval specifies the min. number of eigenvalues/vectors required. This is primarily used in Arnoldi type implementations; direct solvers such as QZ compute all the eigenvalues/vectors. Note: this is a legacy version of this function that stores re & imag parts of eigenvectors in some solver-specific collection of real vectors.
virtual void solve_eigenproblem (Problem *const &problem_pt, const int &n_eval, Vector< std::complex< double > > &eigenvalue, Vector< DoubleVector > &eigenvector_real, Vector< DoubleVector > &eigenvector_imag, const bool &do_adjoint_problem=false)
Solve the real eigenproblem that is assembled by elements in a mesh in a Problem object. Note that the assembled matrices include the shift and are real. The eigenvalues and eigenvectors are, in general, complex, and the eigenvalues can be NaNs or Infs. This function is therefore merely provided as a convenience, to be used if the user is confident that NaNs don't arise (e.g. in Arnoldi based solvers where typically only a small number of (finite) eigenvalues are computed), or if the users is happy to deal with NaNs in the subsequent post-processing. Function is virtual so it can be overloaded for Arnoldi type solvers that compute the (finite) eigenvalues directly At least n_eval eigenvalues are computed.
virtual void solve_eigenproblem (Problem *const &problem_pt, const int &n_eval, Vector< std::complex< double > > &alpha, Vector< double > &beta, Vector< DoubleVector > &eigenvector_real, Vector< DoubleVector > &eigenvector_imag, const bool &do_adjoint_problem=false)=0
Solve the real eigenproblem that is assembled by elements in a mesh in a Problem object. Note that the assembled matrices include the shift and are real. The eigenvalues and eigenvectors are, in general, complex. Eigenvalues may be infinite and are therefore returned as $ \lambda_i = \alpha_i / \beta_i $ where $ \alpha_i $ is complex while $ \beta_i $ is real. The actual eigenvalues may then be computed by doing the division, checking for zero betas to avoid NaNs. There's a convenience wrapper to this function that simply computes these eigenvalues regardless. That version may die in NaN checking is enabled (via the fenv.h header and the associated feenable function). At least n_eval eigenvalues are computed.
void set_shift (const double &shift_value)
Set the value of the (real) shift.
const double & get_shift () const
Return the value of the (real) shift (const version)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
if the communicator_pt is null then the distribution is not setup then false is returned, otherwise return true
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
setup the distribution of this distributable linear algebra object
void build_distribution (const LinearAlgebraDistribution &dist)
setup the distribution of this distributable linear algebra object
Private Types
typedef double ST
typedef Teuchos::ScalarTraits< ST > SCT
typedef SCT::magnitudeType MT
typedef Anasazi::MultiVec< ST > MV
typedef Anasazi::Operator< ST > OP
typedef Anasazi::MultiVecTraits< ST, MV > MVT
typedef Anasazi::OperatorTraits< ST, MV, OP > OPT
Private Attributes
Anasazi::OutputManager< ST > * Output_manager_pt
Pointer to output manager.
LinearSolver * Linear_solver_pt
Pointer to a linear solver.
LinearSolver * Default_linear_solver_pt
Pointer to a default linear solver.
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
clear the distribution of this distributable linear algebra object
Protected Attributes inherited from oomph::EigenSolver
double Sigma_real
Double value that represents the real part of the shift in shifted eigensolvers.
Detailed Description
Class for the Anasazi eigensolver.
Definition at line 673 of file trilinos_eigen_solver.h.
Member Typedef Documentation
MT
typedef SCT::magnitudeType oomph::ANASAZI::MT [private]
Definition at line 678 of file trilinos_eigen_solver.h.
MV
typedef Anasazi::MultiVec<ST> oomph::ANASAZI::MV [private]
Definition at line 679 of file trilinos_eigen_solver.h.
MVT
typedef Anasazi::MultiVecTraits<ST, MV> oomph::ANASAZI::MVT [private]
Definition at line 681 of file trilinos_eigen_solver.h.
OP
typedef Anasazi::Operator<ST> oomph::ANASAZI::OP [private]
Definition at line 680 of file trilinos_eigen_solver.h.
OPT
typedef Anasazi::OperatorTraits<ST, MV, OP> oomph::ANASAZI::OPT [private]
Definition at line 682 of file trilinos_eigen_solver.h.
SCT
typedef Teuchos::ScalarTraits<ST> oomph::ANASAZI::SCT [private]
Definition at line 677 of file trilinos_eigen_solver.h.
ST
typedef double oomph::ANASAZI::ST [private]
Definition at line 676 of file trilinos_eigen_solver.h.
Constructor & Destructor Documentation
ANASAZI() [1/2]
oomph::ANASAZI::ANASAZI () [inline]
Constructor.
Definition at line 711 of file trilinos_eigen_solver.h.
References Output_manager_pt.
ANASAZI() [2/2]
oomph::ANASAZI::ANASAZI (const ANASAZI &) [inline]
Empty copy constructor.
Definition at line 731 of file trilinos_eigen_solver.h.
 ANASAZI()
virtual oomph::ANASAZI::~ANASAZI () [inline], [virtual]
Destructor, delete the linear solver.
Definition at line 734 of file trilinos_eigen_solver.h.
Member Function Documentation
linear_solver_pt() [1/2]
LinearSolver *& oomph::ANASAZI::linear_solver_pt () [inline]
Return a pointer to the linear solver object.
Definition at line 1131 of file trilinos_eigen_solver.h.
References Linear_solver_pt.
Referenced by solve_eigenproblem(), and solve_eigenproblem_legacy().
linear_solver_pt() [2/2]
LinearSolver *const & oomph::ANASAZI::linear_solver_pt () const [inline]
Return a pointer to the linear solver object (const version)
Definition at line 1137 of file trilinos_eigen_solver.h.
References Linear_solver_pt.
solve_eigenproblem() [1/2]
void oomph::ANASAZI::solve_eigenproblem (Problem *const & problem_pt, const int & n_eval, Vector< std::complex< double > > & alpha, Vector< double > & beta, Vector< DoubleVector > & eigenvector_real, Vector< DoubleVector > & eigenvector_imag, const bool & do_adjoint_problem) [inline], [virtual]
Solve the real eigenproblem that is assembled by elements in a mesh in a Problem object. Note that the assembled matrices include the shift and are real. The eigenvalues and eigenvectors are, in general, complex. Eigenvalues may be infinite and are therefore returned as $ \lambda_i = \alpha_i / \beta_i $ where $ \alpha_i $ is complex while $ \beta_i $ is real. The actual eigenvalues may then be computed by doing the division, checking for zero betas to avoid NaNs. There's a convenience wrapper to this function that simply computes these eigenvalues regardless. That version may die in NaN checking is enabled (via the fenv.h header and the associated feenable function). NOTE: While the above statement is true, the implementation of this function is actually everse engineered -- trilinos actually computes the eigenvalues directly (and being an Arnoldi method it wouldn't be able to obtain any infinite/NaN eigenvalues anyway.
Implements oomph::EigenSolver.
Definition at line 775 of file trilinos_eigen_solver.h.
References i, and solve_eigenproblem().
Referenced by solve_eigenproblem().
solve_eigenproblem() [2/2]
void oomph::ANASAZI::solve_eigenproblem (Problem *const & problem_pt, const int & n_eval, Vector< std::complex< double > > & eigenvalue, Vector< DoubleVector > & eigenvector_real, Vector< DoubleVector > & eigenvector_imag, const bool & do_adjoint_problem) [inline], [virtual]
Solve the eigen problem.
Reimplemented from oomph::EigenSolver.
Definition at line 802 of file trilinos_eigen_solver.h.
References oomph::Problem::create_new_linear_algebra_distribution(), i, oomph::Problem::linear_solver_pt(), Linear_solver_pt, linear_solver_pt(), oomph::DistributableLinearAlgebraObject::nrow_local(), oomph::oomph_info, and oomph::EigenSolver::Sigma_real.
solve_eigenproblem_legacy()
void oomph::ANASAZI::solve_eigenproblem_legacy (Problem *const & problem_pt, const int & n_eval, Vector< std::complex< double > > & eigenvalue, Vector< DoubleVector > & eigenvector, const bool & do_adjoint_problem) [inline], [virtual]
Solve the eigen problem.
Implements oomph::EigenSolver.
Definition at line 987 of file trilinos_eigen_solver.h.
References oomph::Problem::dof_distribution_pt(), i, oomph::Problem::linear_solver_pt(), Linear_solver_pt, linear_solver_pt(), oomph::DistributableLinearAlgebraObject::nrow_local(), oomph::oomph_info, and oomph::EigenSolver::Sigma_real.
Member Data Documentation
Default_linear_solver_pt
LinearSolver* oomph::ANASAZI::Default_linear_solver_pt [private]
Pointer to a default linear solver.
Definition at line 691 of file trilinos_eigen_solver.h.
Linear_solver_pt
LinearSolver* oomph::ANASAZI::Linear_solver_pt [private]
Pointer to a linear solver.
Definition at line 688 of file trilinos_eigen_solver.h.
Referenced by linear_solver_pt(), solve_eigenproblem(), and solve_eigenproblem_legacy().
Output_manager_pt
Anasazi::OutputManager<ST>* oomph::ANASAZI::Output_manager_pt [private]
Pointer to output manager.
Definition at line 685 of file trilinos_eigen_solver.h.
Referenced by ANASAZI().
The documentation for this class was generated from the following file:
trilinos_eigen_solver.h