oomph::DenseComplexMatrix Class Reference
Class of matrices containing double complex, and stored as a DenseMatrix<complex<double> >, but with solving functionality inherited from the abstract ComplexMatrix class.
#include <complex_matrices.h>
Public Member Functions
DenseComplexMatrix ()
Empty constructor, simply assign the lengths N and M to 0.
DenseComplexMatrix (const unsigned long &n)
Constructor to build a square n by n matrix.
DenseComplexMatrix (const unsigned long &n, const unsigned long &m)
Constructor to build a matrix with n rows and m columns.
DenseComplexMatrix (const unsigned long &n, const unsigned long &m, const std::complex< double > &initial_val)
Constructor to build a matrix with n rows and m columns, with initial value initial_val.
DenseComplexMatrix (const DenseComplexMatrix &matrix)=delete
Broken copy constructor.
void operator= (const DenseComplexMatrix &)=delete
Broken assignment operator.
unsigned long nrow () const
Return the number of rows of the matrix.
unsigned long ncol () const
Return the number of columns of the matrix.
std::complex< double > operator() (const unsigned long &i, const unsigned long &j) const
Overload the const version of the round-bracket access operator for read-only access.
std::complex< double > & operator() (const unsigned long &i, const unsigned long &j)
Overload the non-const version of the round-bracket access operator for read-write access.
virtual ~DenseComplexMatrix ()
Destructor, delete the storage for Index vector and LU storage (if any)
int ludecompose ()
Overload the LU decomposition. For this storage scheme the matrix storage will be over-writeen by its LU decomposition.
void lubksub (Vector< std::complex< double > > &rhs)
Overload the LU back substitution. Note that the rhs will be overwritten with the solution vector.
void residual (const Vector< std::complex< double > > &x, const Vector< std::complex< double > > &rhs, Vector< std::complex< double > > &residual)
Find the residual of Ax=b, ie r=b-Ax for the `solution` x.
void multiply (const Vector< std::complex< double > > &x, Vector< std::complex< double > > &soln)
Multiply the matrix by the vector x: soln=Ax.
void multiply_transpose (const Vector< std::complex< double > > &x, Vector< std::complex< double > > &soln)
Multiply the transposed matrix by the vector x: soln=A^T x.
Public Member Functions inherited from oomph::ComplexMatrixBase
ComplexMatrixBase ()
(Empty) constructor.
ComplexMatrixBase (const ComplexMatrixBase &matrix)=delete
Broken copy constructor.
void operator= (const ComplexMatrixBase &)=delete
Broken assignment operator.
virtual unsigned long nrow () const =0
Return the number of rows of the matrix.
virtual unsigned long ncol () const =0
Return the number of columns of the matrix.
virtual ~ComplexMatrixBase ()
virtual (empty) destructor
virtual std::complex< double > operator() (const unsigned long &i, const unsigned long &j) const =0
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!)
virtual int ludecompose ()
LU decomposition of the matrix using the appropriate linear solver. Return the sign of the determinant.
virtual void lubksub (Vector< std::complex< double > > &rhs)
LU backsubstitue a previously LU-decomposed matrix; The passed rhs will be over-written with the solution vector.
virtual void solve (Vector< std::complex< double > > &rhs)
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written.
virtual void solve (const Vector< std::complex< double > > &rhs, Vector< std::complex< double > > &soln)
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten.
virtual void residual (const Vector< std::complex< double > > &x, const Vector< std::complex< double > > &b, Vector< std::complex< double > > &residual)=0
Find the residual, i.e. r=b-Ax the residual.
virtual double max_residual (const Vector< std::complex< double > > &x, const Vector< std::complex< double > > &rhs)
Find the maximum residual r=b-Ax -- generic version, can be overloaded for specific derived classes where the max. can be determined `on the fly`.
virtual void multiply (const Vector< std::complex< double > > &x, Vector< std::complex< double > > &soln)=0
Multiply the matrix by the vector x: soln=Ax.
virtual void multiply_transpose (const Vector< std::complex< double > > &x, Vector< std::complex< double > > &soln)=0
Multiply the transposed matrix by the vector x: soln=A^T x.
Public Member Functions inherited from oomph::DenseMatrix< std::complex< double > >
DenseMatrix ()
Empty constructor, simply assign the lengths N and M to 0.
DenseMatrix (const DenseMatrix &source_matrix)
Copy constructor: Deep copy!
DenseMatrix (const unsigned long &n)
Constructor to build a square n by n matrix.
DenseMatrix (const unsigned long &n, const unsigned long &m)
Constructor to build a matrix with n rows and m columns.
DenseMatrix (const unsigned long &n, const unsigned long &m, const std::complex< double > &initial_val)
Constructor to build a matrix with n rows and m columns, with initial value initial_val.
DenseMatrix & operator= (const DenseMatrix &source_matrix)
Copy assignment.
std::complex< double > & entry (const unsigned long &i, const unsigned long &j)
The access function that will be called by the read-write round-bracket operator.
std::complex< double > get_entry (const unsigned long &i, const unsigned long &j) const
The access function the will be called by the read-only (const version) round-bracket operator.
virtual ~DenseMatrix ()
Destructor, clean up the matrix data.
unsigned long nrow () const
Return the number of rows of the matrix.
unsigned long ncol () const
Return the number of columns of the matrix.
void resize (const unsigned long &n)
Resize to a square nxn matrix; any values already present will be transfered.
void resize (const unsigned long &n, const unsigned long &m)
Resize to a non-square n x m matrix; any values already present will be transfered.
void resize (const unsigned long &n, const unsigned long &m, const std::complex< double > &initial_value)
Resize to a non-square n x m matrix and initialize the new values to initial_value.
void initialise (const std::complex< double > &val)
Initialize all values in the matrix to val.
void output (std::ostream &outfile) const
Output function to print a matrix row-by-row to the stream outfile.
void output (std::string filename) const
Output function to print a matrix row-by-row to a file. Specify filename.
void indexed_output (std::ostream &outfile) const
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j)
void indexed_output (std::string filename) const
Indexed output function to print a matrix to a file as i,j,a(i,j). Specify filename.
void output_bottom_right_zero_helper (std::ostream &outfile) const
Output the `bottom right` entry regardless of it being zero or not (this allows automatic detection of matrix size in e.g. matlab, python).
void sparse_indexed_output_helper (std::ostream &outfile) const
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j) for a(i,j)!=0 only.
Public Member Functions inherited from oomph::Matrix< T, MATRIX_TYPE >
Matrix ()
(Empty) constructor
Matrix (const Matrix &matrix)=delete
Broken copy constructor.
void operator= (const Matrix &)=delete
Broken assignment operator.
virtual ~Matrix ()
Virtual (empty) destructor.
virtual unsigned long nrow () const =0
Return the number of rows of the matrix.
virtual unsigned long ncol () const =0
Return the number of columns of the matrix.
T operator() (const unsigned long &i, const unsigned long &j) const
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!) The function uses the MATRIX_TYPE template parameter to call the get_entry() function which must be defined in all derived classes that are to be fully instantiated.
T & operator() (const unsigned long &i, const unsigned long &j)
Round brackets to give access as a(i,j) for read-write access. The function uses the MATRIX_TYPE template parameter to call the entry() function which must be defined in all derived classes that are to be fully instantiated. If the particular Matrix does not allow write access, the function should break with an error message.
virtual void output (std::ostream &outfile) const
Output function to print a matrix row-by-row, in the form a(0,0) a(0,1) ... a(1,0) a(1,1) ... ... to the stream outfile. Broken virtual since it might not be sensible to implement this for some sparse matrices.
virtual void output_bottom_right_zero_helper (std::ostream &outfile) const =0
Output the `bottom right` entry regardless of it being zero or not (this allows automatic detection of matrix size in e.g. matlab, python). This functionality was moved from the function sparse_indexed_output(...) because at the moment, generalisation of this functionality does not work in parallel. CRDoubleMatrix has an nrow() function but it should it should use nrow_local() - which is the N variable in the underlaying CRMatrix.
virtual void sparse_indexed_output_helper (std::ostream &outfile) const =0
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j) for a(i,j)!=0 only.
void sparse_indexed_output (std::ostream &outfile, const unsigned &precision=0, const bool &output_bottom_right_zero=false) const
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j) for a(i,j)!=0 only with specified precision (if precision=0 then nothing is changed). If optional boolean flag is set to true we also output the `bottom right` entry regardless of it being zero or not (this allows automatic detection of matrix size in e.g. matlab, python).
void sparse_indexed_output (std::string filename, const unsigned &precision=0, const bool &output_bottom_right_zero=false) const
Indexed output function to print a matrix to the file named filename as i,j,a(i,j) for a(i,j)!=0 only with specified precision. If optional boolean flag is set to true we also output the `bottom right` entry regardless of it being zero or not (this allows automatic detection of matrix size in e.g. matlab, python).
Private Member Functions
void delete_lu_factors ()
Function that deletes the storage for the LU_factors, if it is not the same as the matrix storage.
Private Attributes
Vector< long > * Index
Pointer to storage for the index of permutations in the LU solve.
std::complex< double > * LU_factors
Pointer to storage for the LU decomposition.
bool Overwrite_matrix_storage
Boolean flag used to decided whether the LU decomposition is stored separately, or not.
Additional Inherited Members
Protected Member Functions inherited from oomph::Matrix< T, MATRIX_TYPE >
void range_check (const unsigned long &i, const unsigned long &j) const
Range check to catch when an index is out of bounds, if so, it issues a warning message and dies by throwing an OomphLibError.
Protected Attributes inherited from oomph::DenseMatrix< std::complex< double > >
std::complex< double > * Matrixdata
Internal representation of matrix as a pointer to data.
unsigned long N
Number of rows.
unsigned long M
Number of columns.
Detailed Description
Class of matrices containing double complex, and stored as a DenseMatrix<complex<double> >, but with solving functionality inherited from the abstract ComplexMatrix class.
Definition at line 153 of file complex_matrices.h.
Constructor & Destructor Documentation
DenseComplexMatrix() [1/5]
oomph::DenseComplexMatrix::DenseComplexMatrix () [inline]
Empty constructor, simply assign the lengths N and M to 0.
Definition at line 173 of file complex_matrices.h.
DenseComplexMatrix() [2/5]
oomph::DenseComplexMatrix::DenseComplexMatrix (const unsigned long & n) [inline]
Constructor to build a square n by n matrix.
Definition at line 182 of file complex_matrices.h.
DenseComplexMatrix() [3/5]
oomph::DenseComplexMatrix::DenseComplexMatrix (const unsigned long & n, const unsigned long & m) [inline]
Constructor to build a matrix with n rows and m columns.
Definition at line 191 of file complex_matrices.h.
DenseComplexMatrix() [4/5]
oomph::DenseComplexMatrix::DenseComplexMatrix (const unsigned long & n, const unsigned long & m, const std::complex< double > & initial_val) [inline]
Constructor to build a matrix with n rows and m columns, with initial value initial_val.
Definition at line 201 of file complex_matrices.h.
DenseComplexMatrix() [5/5]
oomph::DenseComplexMatrix::DenseComplexMatrix (const DenseComplexMatrix & matrix) [delete]
Broken copy constructor.
 DenseComplexMatrix()
oomph::DenseComplexMatrix::~DenseComplexMatrix () [virtual]
Destructor, delete the storage for Index vector and LU storage (if any)
Destructor clean up the LU factors that have been allocated.
Definition at line 104 of file complex_matrices.cc.
References Index, and LU_factors.
Member Function Documentation
delete_lu_factors()
void oomph::DenseComplexMatrix::delete_lu_factors () [private]
Function that deletes the storage for the LU_factors, if it is not the same as the matrix storage.
Delete the storage that has been allocated for the LU factors, if the matrix data is not itself being overwritten.
Definition at line 87 of file complex_matrices.cc.
References LU_factors, and Overwrite_matrix_storage.
Referenced by ludecompose().
lubksub()
void oomph::DenseComplexMatrix::lubksub (Vector< std::complex< double > > & rhs) [virtual]
Overload the LU back substitution. Note that the rhs will be overwritten with the solution vector.
Back substitute an LU decomposed matrix.
Reimplemented from oomph::ComplexMatrixBase.
Definition at line 374 of file complex_matrices.cc.
References i, Index, LU_factors, oomph::DenseMatrix< std::complex< double > >::M, and oomph::DenseMatrix< std::complex< double > >::N.
ludecompose()
int oomph::DenseComplexMatrix::ludecompose () [virtual]
Overload the LU decomposition. For this storage scheme the matrix storage will be over-writeen by its LU decomposition.
LU decompose a matrix, over-writing it and recording the pivots numbers in the Index vector. Returns the sign of the determinant.
Reimplemented from oomph::ComplexMatrixBase.
Definition at line 121 of file complex_matrices.cc.
References delete_lu_factors(), oomph::DenseMatrix< std::complex< double > >::entry(), i, Index, LU_factors, oomph::DenseMatrix< std::complex< double > >::M, oomph::DenseMatrix< std::complex< double > >::Matrixdata, oomph::DenseMatrix< std::complex< double > >::N, and Overwrite_matrix_storage.
multiply()
void oomph::DenseComplexMatrix::multiply (const Vector< std::complex< double > > & x, Vector< std::complex< double > > & soln) [virtual]
Multiply the matrix by the vector x: soln=Ax.
Implements oomph::ComplexMatrixBase.
Definition at line 507 of file complex_matrices.cc.
References i, oomph::DenseMatrix< std::complex< double > >::M, oomph::DenseMatrix< std::complex< double > >::Matrixdata, and oomph::DenseMatrix< std::complex< double > >::N.
multiply_transpose()
void oomph::DenseComplexMatrix::multiply_transpose (const Vector< std::complex< double > > & x, Vector< std::complex< double > > & soln) [virtual]
Multiply the transposed matrix by the vector x: soln=A^T x.
Implements oomph::ComplexMatrixBase.
Definition at line 545 of file complex_matrices.cc.
References i, oomph::DenseMatrix< std::complex< double > >::M, oomph::DenseMatrix< std::complex< double > >::Matrixdata, and oomph::DenseMatrix< std::complex< double > >::N.
ncol()
unsigned long oomph::DenseComplexMatrix::ncol () const [inline], [virtual]
Return the number of columns of the matrix.
Implements oomph::ComplexMatrixBase.
Definition at line 225 of file complex_matrices.h.
References ncol().
Referenced by ncol().
nrow()
unsigned long oomph::DenseComplexMatrix::nrow () const [inline], [virtual]
Return the number of rows of the matrix.
Implements oomph::ComplexMatrixBase.
Definition at line 219 of file complex_matrices.h.
References nrow().
Referenced by nrow().
operator()() [1/2]
std::complex< double > & oomph::DenseComplexMatrix::operator() (const unsigned long & i, const unsigned long & j) [inline]
Overload the non-const version of the round-bracket access operator for read-write access.
Definition at line 240 of file complex_matrices.h.
References oomph::DenseMatrix< std::complex< double > >::entry(), and i.
operator()() [2/2]
std::complex< double > oomph::DenseComplexMatrix::operator() (const unsigned long & i, const unsigned long & j) const [inline], [virtual]
Overload the const version of the round-bracket access operator for read-only access.
Implements oomph::ComplexMatrixBase.
Definition at line 232 of file complex_matrices.h.
References oomph::DenseMatrix< std::complex< double > >::get_entry(), and i.
operator=()
void oomph::DenseComplexMatrix::operator= (const DenseComplexMatrix &) [delete]
Broken assignment operator.
residual()
void oomph::DenseComplexMatrix::residual (const Vector< std::complex< double > > & x, const Vector< std::complex< double > > & rhs, Vector< std::complex< double > > & residual) [virtual]
Find the residual of Ax=b, ie r=b-Ax for the `solution` x.
Find the residual of Ax=b, i.e. r=b-Ax.
Implements oomph::ComplexMatrixBase.
Definition at line 450 of file complex_matrices.cc.
References i, oomph::DenseMatrix< std::complex< double > >::M, oomph::DenseMatrix< std::complex< double > >::Matrixdata, oomph::DenseMatrix< std::complex< double > >::N, and residual().
Referenced by residual().
Member Data Documentation
Index
Vector<long>* oomph::DenseComplexMatrix::Index [private]
Pointer to storage for the index of permutations in the LU solve.
Definition at line 158 of file complex_matrices.h.
Referenced by lubksub(), ludecompose(), and ~DenseComplexMatrix().
LU_factors
std::complex<double>* oomph::DenseComplexMatrix::LU_factors [private]
Pointer to storage for the LU decomposition.
Definition at line 161 of file complex_matrices.h.
Referenced by delete_lu_factors(), lubksub(), ludecompose(), and ~DenseComplexMatrix().
Overwrite_matrix_storage
bool oomph::DenseComplexMatrix::Overwrite_matrix_storage [private]
Boolean flag used to decided whether the LU decomposition is stored separately, or not.
Definition at line 165 of file complex_matrices.h.
Referenced by delete_lu_factors(), and ludecompose().
The documentation for this class was generated from the following files:
complex_matrices.h
complex_matrices.cc